// apps/ash-qrb-client/app/pages/(security)/sign-up/index.vue
<script setup lang="ts">
import DefaultCard from "~/components/cards/DefaultCard.vue";

const { t } = useI18n()
</script>

<template>
  <section class="section-sign-up">
    <div class="container">
      <div class="container h-full">
        <div class="w-full min-h-[65vh] flex justify-center items-center">
          <DefaultCard :title="t('formActionSignUp')">

          </DefaultCard>
        </div>
      </div>
    </div>
  </section>
</template>

<style scoped>

</style>

// packages/ash-qrb-client/src/pages/s/sign-up/index.tsx
import SectionHomeTitle from '@root/components/sections/home/SectionHomeTitle';
import { useTranslate } from '@tolgee/react';
import QrbFormSignUp from '@root/components/qrb-form-sign-up/QrbFormSignUp';

export default function SignUp() {
  const { t } = useTranslate();
  return (
    <>
      <SectionHomeTitle title={t('page.signup.h1')} />
      <section className="page-signup">
        <div className="container">
          <div className="w-full max-w-lg flex py-5">
            <QrbFormSignUp />
          </div>
        </div>
      </section>
    </>
  );
}
